<a href="https://colab.research.google.com/github/Nidzoki/PMFSTMachineLearning/blob/main/vjezba1/2_Pisanje_i_izvrsavanje_Python_koda_(zad).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![thumbnail](https://drive.google.com/uc?id=1P_Mbcld2ZKcp5rUZuaa6Hrz8_d5G37Hf)

# **2. Pisanje i izvršavanje Python koda**

1. Izvršavanje trenutne ćelije s kodom: Klikom na **play** ikonu $\iff$ **Ctrl + Enter**.

2. Izvršavanje trenutne ćelije s kodom s prebacivanjem fokusa na sljedeću ćeliju: **Shift + Enter**.

3. Izvršavanje trenutne ćelije s dodavanjem nove ćelije ispod: **Alt + Enter**.




In [1]:
print('Hello world!')

Hello world!


In [2]:
def HelloWorld(n):
  '''
  Funkcija koja ispisuje "Hello world!" n puta.
  '''
  for i in range(n):
    print('Hello world!')

In [3]:
HelloWorld(5)

Hello world!
Hello world!
Hello world!
Hello world!
Hello world!


In [4]:
a = 5
b = 7
a + b

12

#### Izvršavanje više ćelija odjednom

---

- Izvršavanje svih ćelija: **Runtime $\to$ Run all**.
- Izvršavanje svih ćelija koje su iznad trenutno aktivne ćelije: **Runtime $\to$ Run before**.
- Izvršavanje svih ćelija koje su iznad trenutno aktivne ćelije: **Runtime $\to$ Run after**.
- Izvršavanje samo odabranih ćelija:
  1. označiti ćelije koje želimo izvršiti (**Ctrl + lijevi klik miša**)
  2.  **Runtime $\to$ Run selection**.


## Učitavanje/instaliranje biblioteka


Colaboratory dolazi s velikim brojem predinstaliranih biblioteka koje učitavamo u bilježnice koristeći  ključnu riječ `import`.

Učitajmo predinstaliranu biblioteku [`NumPy`](https://numpy.org/) koja se koristi za znanstveno računanje u Pythonu.


In [5]:
import numpy as np

In [6]:
A = np.random.randn(5,5)
A

array([[-0.04522828,  1.87870371, -0.39264136, -1.59908254, -0.86296827],
       [-1.5002109 ,  0.71070592, -0.08655831,  0.32105263,  0.33253093],
       [-1.10482162,  1.72276738,  0.43190427,  0.87680375,  2.5200102 ],
       [ 0.99893398,  1.72495846,  1.09174206, -1.40862481, -0.75382688],
       [ 0.82545106,  0.85390007,  0.80294501, -1.50358141, -1.74600525]])

Za otvaranje dostupne dokumentacije dodajte **?** nakon imena metode

In [7]:
np.random.randn?

In [ ]:
print('max: {}'.format(np.max(A)))
print('avg: {}'.format(np.mean(A)))

### Pakete/biblioteke koji nisu predinstalirani možemo sami instalirati koristeći `pip` naredbu.


In [8]:
import py3dmol

ModuleNotFoundError: No module named 'py3dmol'

Paket koji omogućuje interaktivni 3D prikaz molekula u bilježnicama.

In [9]:
!pip install py3dmol

In [10]:
import py3Dmol
p = py3Dmol.view(query = 'mmtf:1ycr')
p.setStyle({'cartoon': {'color': 'spectrum'}})

3Dmol.js failed to load for some reason. Please check your browser console for error messages.

## Prekidanje izvršavanja ćelije


> 2 načina:
- pritiskom **stop** ikone
-  **Runtime -> Interrupt execution**
(*shortcut: Ctrl-M I*)

In [11]:
import time
print("Spavam....")
time.sleep(60) # odgodi daljnje izvršavanje koda za 1 min
print("Gotovo!")

Spavam....


KeyboardInterrupt: 

In [12]:
time.sleep?

# Zadaci

Kao pomoć pri rješavanju zadatka koristite [NumPy dokumentaciju](https://docs.scipy.org/doc/numpy-1.16.0/reference/index.html).






<br>












## Zadatak 1

Generirajte dva numpy arraya dimenzija $2\times 3$ kojima su elementi slučajno generirani cijeli brojevi iz raspona $[1,7 \rangle$.

1. Ispišite generirane numpy arraye.
2. Transformirajte generirane numpy arraye u vektore i izračunajte njihov skalarni produkt.





In [13]:
## 1
import random as rn
import numpy as np

a = np.array([[rn.randint(1,7) for i in range(3)] for j in range(2)])
b = np.array([[rn.randint(1,7) for i in range(3)] for j in range(2)])

print(a)
print(b)


[[6 3 2]
 [7 3 2]]
[[6 6 5]
 [2 7 5]]


In [15]:
## 2
print(np.dot(a.flatten(), b.flatten()))


109


## Zadatak 2.

Napišite funkciju **Multiply** koja kao ulazne parametre prima prirodne brojeve $a$, $b$, $c$ i $d$  te kao rezultat vraća ***umnožak matrica*** dimenzija $a\times b$  te  $c\times d$ (ako je umnožak moguće izračunati).   Svaka matrica je reprezentirana jednim numpy arrayem kojem su elementi slučajno generirani  cijeli brojevi iz raspona $[1,7 \rangle$. Ako umnožak nije moguće izračunati, potrebno je ispisati poruku o tome.

> Napomena: Negdje ispišite generirane matrice.



In [16]:
import numpy as np
import random as rn

def Multiply(a, b, c, d):
  return "Nemoguće izračunati" if b != c else np.dot(np.array([[rn.randint(1,7) for i in range(b)] for j in range(a)]), np.array([[rn.randint(1,7) for i in range(d)] for j in range(c)]))

In [17]:
C = Multiply(2, 3, 3, 5)

print(f"C: {C}")
print(f"C.shape = {C.shape}")

C: [[72 27 27 31 40]
 [73 41 41 44 58]]
C.shape = (2, 5)


In [18]:
C = Multiply(2, 3, 4, 5)
print(C)
print(C.shape)

Nemoguće izračunati


AttributeError: 'str' object has no attribute 'shape'

# **Dodatni** zadaci za vježbu
> <mark>*NIJE OBAVEZNO...*<mark>


## Zadatak 1.
 Napišite funkciju **RandomArray** koja kao ulazne parametre prima dva prirodna broja $m, n$ i string $d \in \{ \text{"uniform", "normal", "poisson"} \}$ te kao rezultat vraća $m\times n$ numpy array slučajnih brojeva generiranih iz distribucije $d$.

<br>

> *Napomena:*
>
>
>Parametre distribucije
> - $\mu$ i $\sigma$ kod normalne
> - granice $min$ i $max$ kod uniformne
> - $\lambda$ kod Poissonove
>
> unosi korisnik (unos unutar metode).

Ako nije poslan "ispravan" parametar $d$, onda se brojevi generiraju iz standardne normalne distribucije ($\mu = 0$, $\sigma = 1$).












Kao pomoć pri rješavanju zadataka koristite [NumPy dokumentaciju](https://docs.scipy.org/doc/numpy-1.16.0/reference/index.html).

In [26]:
import numpy as np

def RandomArray(m, n, d):

  if d == "uniform":
    min_val = float(input("Unesi minimalnu vrijednost za uniformnu distribuciju: "))
    max_val = float(input("Unesi maksimalnu vrijednost za uniformnu distribuciju: "))
    return np.random.uniform(min_val, max_val, size=(m, n))
  elif d == "normal":
    mu = float(input("Unesi mean (mu) za normalnu distribuciju: "))
    sigma = float(input("Unesi standardnu devijaciju (sigma) za normalnu distribuciju: "))
    return np.random.normal(mu, sigma, size=(m, n))
  elif d == "poisson":
    lam = float(input("Unesi lambdau za Poissonovu distribuciju: "))
    return np.random.poisson(lam, size=(m, n))
  else:
    print("Pogrešan parametar. Koristi se standardna normalna distribucija (mu=0, sigma=1).")
    return np.random.normal(0, 1, size=(m, n))

### Test

In [20]:
m, n = 5, 7

In [27]:
A = RandomArray(m, n, "nn")
print(A)
print(A.shape)

Pogrešan parametar. Koristi se standardna normalna distribucija (mu=0, sigma=1).
[[-0.6916707   0.86968479  0.29382415 -1.93466305 -0.22852791 -1.88685132
   0.18736752]
 [-0.62840551 -0.82595746  1.14536533  0.29197884 -0.46079944 -0.70910208
   0.30306479]
 [ 1.23616268  1.13980854  0.70022795  0.0634431   0.2619108   0.60750299
   1.65015347]
 [ 0.4258583   0.86320328 -0.53386988 -0.21184532 -0.11009728 -1.28055086
  -1.24236336]
 [ 0.4285145   0.43381689  1.45927748  0.4009661  -0.64615894  0.42447262
   2.30101427]]
(5, 7)


In [28]:
A = RandomArray(m, n, "poisson")
print(A)
print(A.shape)

Unesi lambdau za Poissonovu distribuciju: 1
[[0 0 3 2 0 1 2]
 [1 2 1 1 1 0 2]
 [2 0 1 3 3 2 1]
 [0 0 2 1 2 1 1]
 [1 0 2 0 1 1 2]]
(5, 7)


In [29]:
A = RandomArray(m, n, "normal")
print(A)
print(A.shape)

Unesi mean (mu) za normalnu distribuciju: 0
Unesi standardnu devijaciju (sigma) za normalnu distribuciju: 1
[[ 0.18256507  0.56423033  1.14980832  0.840053   -1.75997034 -0.48208108
   1.92569227]
 [ 0.6965511  -1.04839042 -1.32745352  1.37009172  1.24468499  0.31562448
  -1.10515049]
 [ 0.77979141 -0.38653316 -0.6243019   1.14998911  0.18697099 -0.17762135
  -0.20629658]
 [ 0.47868375  1.23446692  0.25540093 -1.7025879   0.61807992 -1.81038794
  -0.92153341]
 [-0.00246939 -0.6515448   0.04432968 -1.53615741 -0.69700658  1.31887246
  -0.50036384]]
(5, 7)


In [30]:
A = RandomArray(m, n, "uniform")
print(A)
print(A.shape)

Unesi minimalnu vrijednost za uniformnu distribuciju: 10
Unesi maksimalnu vrijednost za uniformnu distribuciju: 20
[[19.723394   11.01691696 15.50581861 10.66411068 15.19117717 15.29278305
  15.92886342]
 [18.49858768 15.03547793 10.91971881 18.98080886 14.26759416 11.65765804
  10.25165091]
 [15.38476176 18.35544819 15.47679261 14.50295722 16.8919794  12.15102988
  10.80022298]
 [14.05767557 15.0893814  19.6489626  12.76474599 14.77569413 12.91074472
  13.10246931]
 [18.24622243 14.63698932 12.94425945 11.22522033 13.96811592 10.75653646
  16.26106772]]
(5, 7)


## Zadatak 2

Pomoću funkcije iz *Zadatka 1* generirajte dva $5 \times 100000$ numpy arrayja **A** i **B** iz normalne distribucije s parametrima
- **A**: $\mu = 50$ i $\sigma = 2$
- **B**: $\mu = -50$ i $\sigma = 2$.

Izračunajte srednje vrijednost **po retcima** za **A**, **B** i **A + B**.
Što uočavate?

Uočavam da su distribucije skoro pa jednake jer smo imali veliku matricu.

In [48]:
# A: mu = 50 i sigma = 2
A = RandomArray(5, 100000, "normal")
# B: mu = -50 i sigma = 2
B = RandomArray(5, 100000, "normal")

Unesi mean (mu) za normalnu distribuciju: 50
Unesi standardnu devijaciju (sigma) za normalnu distribuciju: 2
Unesi mean (mu) za normalnu distribuciju: -50
Unesi standardnu devijaciju (sigma) za normalnu distribuciju: 2


In [49]:
print(f"srednja vrijednost po retcima A:", np.mean(A, axis=1))
print(f"srednja vrijednost po retcima B:", np.mean(B, axis=1))
print(f"srednja vrijednost po retcima A + B:", np.mean(A + B, axis=1))

srednja vrijednost po retcima A: [50.0053953  49.99432574 50.01218406 50.00425323 50.007013  ]
srednja vrijednost po retcima B: [-49.99276346 -49.9934744  -49.98848763 -49.99247659 -50.00292553]
srednja vrijednost po retcima A + B: [0.01263184 0.00085135 0.02369644 0.01177664 0.00408747]
